apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: desk-manager-certificate
  namespace: cert-manager
spec:
  duration: 2160h
  renewBefore: 360h
  secretName: desk-manager-certificate-secret
  issuerRef:
    name: ca-issuer           
    kind: Issuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "hello-world,desk-manager,keycloak"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "hello-world,desk-manager,keycloak"
  dnsNames:
  - cbranet.academy.dvloper.io
  - "*.cbranet.academy.dvloper.io"