apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
spec:
  tls:
  - hosts:
    - keycloak.cristian-branet.academy.dvloper.io
    secretName: desk-manager-certificate-secret
  rules:
  - host: keycloak.cristian-branet.academy.dvloper.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 80