apiVersion: apps/v1
kind: Deployment
metadata:
  name: desk-manager-frontend
  namespace: desk-manager
  labels:
    app: desk-manager-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: desk-manager-frontend
  template:
    metadata:
      labels:
        app: desk-manager-frontend
    spec:
      imagePullSecrets:
      - name: harbor-credentials
      containers:
      - name: frontend
        image: harbor.dvloper.io/desk-manager-cristian-branet/desk-manager-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_KEYCLOAK_URL
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: VITE_KEYCLOAK_URL
        - name: VITE_KEYCLOAK_REALM
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: VITE_KEYCLOAK_REALM
        - name: VITE_KEYCLOAK_CLIENT
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: VITE_KEYCLOAK_CLIENT
        - name: VITE_BACKEND_API_URL
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: VITE_BACKEND_API_URL
        - name: VITE_REQUIRED_ROLE
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: VITE_REQUIRED_ROLE
---
apiVersion: v1
kind: Service
metadata:
  name: desk-manager-frontend-service
  namespace: desk-manager
  labels:
    app: desk-manager-frontend
spec:
  selector:
    app: desk-manager-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: desk-manager-frontend-ingress
  namespace: desk-manager
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: desk-manager.cbranet.academy.dvloper.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: desk-manager-frontend-service
            port:
              number: 80
  tls:
  - hosts:
    - desk-manager.cbranet.academy.dvloper.io
    secretName: desk-manager-certificate-secret